<?php
/**
 * PriceReductionsV1Api
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Otto\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\Otto\ApiException;
use OpenAPI\Client\Otto\Configuration;
use OpenAPI\Client\Otto\HeaderSelector;
use OpenAPI\Client\Otto\ObjectSerializer;

/**
 * PriceReductionsV1Api Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PriceReductionsV1Api
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'priceReductionsV1ApplyPriceReduction' => [
            'application/json',
        ],
        'priceReductionsV1GetAllReductionsForPartner' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation priceReductionsV1ApplyPriceReduction
     *
     * Apply price reduction for a positionItemId
     *
     * @param  \OpenAPI\Client\Otto\Model\PartnerPriceReductionRequestPriceReductionsV1 $partnerPriceReductionRequestPriceReductionsV1 partnerPriceReductionRequestPriceReductionsV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1ApplyPriceReduction'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1|\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1|\OpenAPI\Client\Otto\Model\NotFoundPositionItemIdPriceReductionsV1|\OpenAPI\Client\Otto\Model\ConflictPositionItemIdPriceReductionsV1|\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1|\OpenAPI\Client\Otto\Model\InternalServerErrorApplyPriceReductionPriceReductionsV1
     */
    public function priceReductionsV1ApplyPriceReduction($partnerPriceReductionRequestPriceReductionsV1, string $contentType = self::contentTypes['priceReductionsV1ApplyPriceReduction'][0])
    {
        list($response) = $this->priceReductionsV1ApplyPriceReductionWithHttpInfo($partnerPriceReductionRequestPriceReductionsV1, $contentType);
        return $response;
    }

    /**
     * Operation priceReductionsV1ApplyPriceReductionWithHttpInfo
     *
     * Apply price reduction for a positionItemId
     *
     * @param  \OpenAPI\Client\Otto\Model\PartnerPriceReductionRequestPriceReductionsV1 $partnerPriceReductionRequestPriceReductionsV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1ApplyPriceReduction'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1|\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1|\OpenAPI\Client\Otto\Model\NotFoundPositionItemIdPriceReductionsV1|\OpenAPI\Client\Otto\Model\ConflictPositionItemIdPriceReductionsV1|\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1|\OpenAPI\Client\Otto\Model\InternalServerErrorApplyPriceReductionPriceReductionsV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function priceReductionsV1ApplyPriceReductionWithHttpInfo($partnerPriceReductionRequestPriceReductionsV1, string $contentType = self::contentTypes['priceReductionsV1ApplyPriceReduction'][0])
    {
        $request = $this->priceReductionsV1ApplyPriceReductionRequest($partnerPriceReductionRequestPriceReductionsV1, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    if ('\OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Otto\Model\NotFoundPositionItemIdPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\NotFoundPositionItemIdPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\NotFoundPositionItemIdPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\OpenAPI\Client\Otto\Model\ConflictPositionItemIdPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\ConflictPositionItemIdPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\ConflictPositionItemIdPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 424:
                    if ('\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Otto\Model\InternalServerErrorApplyPriceReductionPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\InternalServerErrorApplyPriceReductionPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\InternalServerErrorApplyPriceReductionPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\NotFoundPositionItemIdPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\ConflictPositionItemIdPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 424:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\InternalServerErrorApplyPriceReductionPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation priceReductionsV1ApplyPriceReductionAsync
     *
     * Apply price reduction for a positionItemId
     *
     * @param  \OpenAPI\Client\Otto\Model\PartnerPriceReductionRequestPriceReductionsV1 $partnerPriceReductionRequestPriceReductionsV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1ApplyPriceReduction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function priceReductionsV1ApplyPriceReductionAsync($partnerPriceReductionRequestPriceReductionsV1, string $contentType = self::contentTypes['priceReductionsV1ApplyPriceReduction'][0])
    {
        return $this->priceReductionsV1ApplyPriceReductionAsyncWithHttpInfo($partnerPriceReductionRequestPriceReductionsV1, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation priceReductionsV1ApplyPriceReductionAsyncWithHttpInfo
     *
     * Apply price reduction for a positionItemId
     *
     * @param  \OpenAPI\Client\Otto\Model\PartnerPriceReductionRequestPriceReductionsV1 $partnerPriceReductionRequestPriceReductionsV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1ApplyPriceReduction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function priceReductionsV1ApplyPriceReductionAsyncWithHttpInfo($partnerPriceReductionRequestPriceReductionsV1, string $contentType = self::contentTypes['priceReductionsV1ApplyPriceReduction'][0])
    {
        $returnType = '\OpenAPI\Client\Otto\Model\AcceptedPriceReductionResponsePriceReductionsV1';
        $request = $this->priceReductionsV1ApplyPriceReductionRequest($partnerPriceReductionRequestPriceReductionsV1, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'priceReductionsV1ApplyPriceReduction'
     *
     * @param  \OpenAPI\Client\Otto\Model\PartnerPriceReductionRequestPriceReductionsV1 $partnerPriceReductionRequestPriceReductionsV1 (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1ApplyPriceReduction'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function priceReductionsV1ApplyPriceReductionRequest($partnerPriceReductionRequestPriceReductionsV1, string $contentType = self::contentTypes['priceReductionsV1ApplyPriceReduction'][0])
    {

        // verify the required parameter 'partnerPriceReductionRequestPriceReductionsV1' is set
        if ($partnerPriceReductionRequestPriceReductionsV1 === null || (is_array($partnerPriceReductionRequestPriceReductionsV1) && count($partnerPriceReductionRequestPriceReductionsV1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $partnerPriceReductionRequestPriceReductionsV1 when calling priceReductionsV1ApplyPriceReduction'
            );
        }


        $resourcePath = '/v1/price-reductions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($partnerPriceReductionRequestPriceReductionsV1)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($partnerPriceReductionRequestPriceReductionsV1));
            } else {
                $httpBody = $partnerPriceReductionRequestPriceReductionsV1;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation priceReductionsV1GetAllReductionsForPartner
     *
     * Get all priceReductions
     *
     * @param  string|null $positionItemId positionItemId for which price reductions are to be fetched (optional)
     * @param  int|null $page Page number to be fetched. Page number should not be less than 1 (optional, default to 1)
     * @param  int|null $limit Number of positionItemIds to be fetched per page. Limit should not exceed 128 (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1GetAllReductionsForPartner'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1|\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1|\OpenAPI\Client\Otto\Model\NotFoundPriceReductionForPositionItemIdPriceReductionsV1|\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1
     */
    public function priceReductionsV1GetAllReductionsForPartner($positionItemId = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['priceReductionsV1GetAllReductionsForPartner'][0])
    {
        list($response) = $this->priceReductionsV1GetAllReductionsForPartnerWithHttpInfo($positionItemId, $page, $limit, $contentType);
        return $response;
    }

    /**
     * Operation priceReductionsV1GetAllReductionsForPartnerWithHttpInfo
     *
     * Get all priceReductions
     *
     * @param  string|null $positionItemId positionItemId for which price reductions are to be fetched (optional)
     * @param  int|null $page Page number to be fetched. Page number should not be less than 1 (optional, default to 1)
     * @param  int|null $limit Number of positionItemIds to be fetched per page. Limit should not exceed 128 (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1GetAllReductionsForPartner'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1|\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1|\OpenAPI\Client\Otto\Model\NotFoundPriceReductionForPositionItemIdPriceReductionsV1|\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function priceReductionsV1GetAllReductionsForPartnerWithHttpInfo($positionItemId = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['priceReductionsV1GetAllReductionsForPartner'][0])
    {
        $request = $this->priceReductionsV1GetAllReductionsForPartnerRequest($positionItemId, $page, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 403:
                    if ('\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Otto\Model\NotFoundPriceReductionForPositionItemIdPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\NotFoundPriceReductionForPositionItemIdPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\NotFoundPriceReductionForPositionItemIdPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 424:
                    if ('\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\ForbiddenApplyPriceReductionPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\NotFoundPriceReductionForPositionItemIdPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 424:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\FailedDependencyPriceReductionsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation priceReductionsV1GetAllReductionsForPartnerAsync
     *
     * Get all priceReductions
     *
     * @param  string|null $positionItemId positionItemId for which price reductions are to be fetched (optional)
     * @param  int|null $page Page number to be fetched. Page number should not be less than 1 (optional, default to 1)
     * @param  int|null $limit Number of positionItemIds to be fetched per page. Limit should not exceed 128 (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1GetAllReductionsForPartner'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function priceReductionsV1GetAllReductionsForPartnerAsync($positionItemId = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['priceReductionsV1GetAllReductionsForPartner'][0])
    {
        return $this->priceReductionsV1GetAllReductionsForPartnerAsyncWithHttpInfo($positionItemId, $page, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation priceReductionsV1GetAllReductionsForPartnerAsyncWithHttpInfo
     *
     * Get all priceReductions
     *
     * @param  string|null $positionItemId positionItemId for which price reductions are to be fetched (optional)
     * @param  int|null $page Page number to be fetched. Page number should not be less than 1 (optional, default to 1)
     * @param  int|null $limit Number of positionItemIds to be fetched per page. Limit should not exceed 128 (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1GetAllReductionsForPartner'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function priceReductionsV1GetAllReductionsForPartnerAsyncWithHttpInfo($positionItemId = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['priceReductionsV1GetAllReductionsForPartner'][0])
    {
        $returnType = '\OpenAPI\Client\Otto\Model\PriceReductionsResponsePriceReductionsV1';
        $request = $this->priceReductionsV1GetAllReductionsForPartnerRequest($positionItemId, $page, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'priceReductionsV1GetAllReductionsForPartner'
     *
     * @param  string|null $positionItemId positionItemId for which price reductions are to be fetched (optional)
     * @param  int|null $page Page number to be fetched. Page number should not be less than 1 (optional, default to 1)
     * @param  int|null $limit Number of positionItemIds to be fetched per page. Limit should not exceed 128 (optional, default to 10)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['priceReductionsV1GetAllReductionsForPartner'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function priceReductionsV1GetAllReductionsForPartnerRequest($positionItemId = null, $page = 1, $limit = 10, string $contentType = self::contentTypes['priceReductionsV1GetAllReductionsForPartner'][0])
    {





        $resourcePath = '/v1/price-reductions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $positionItemId,
            'positionItemId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
