<?php
/**
 * ShippingProfilesV1Api
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Otto\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\Otto\ApiException;
use OpenAPI\Client\Otto\Configuration;
use OpenAPI\Client\Otto\HeaderSelector;
use OpenAPI\Client\Otto\ObjectSerializer;

/**
 * ShippingProfilesV1Api Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShippingProfilesV1Api
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'shippingProfilesV1CreateShippingProfile' => [
            'application/json;charset=UTF-8',
        ],
        'shippingProfilesV1DeleteShippingProfile' => [
            'application/json',
        ],
        'shippingProfilesV1GetShippingProfileById' => [
            'application/json',
        ],
        'shippingProfilesV1GetShippingProfiles' => [
            'application/json',
        ],
        'shippingProfilesV1UpdateShippingProfile' => [
            'application/json;charset=UTF-8',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfile
     *
     * Create shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 create shipping profile (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1CreateShippingProfile'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIErrorResponseForBadRequestShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIErrorResponseForConflictShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1
     */
    public function shippingProfilesV1CreateShippingProfile($authorization, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1CreateShippingProfile'][0])
    {
        list($response) = $this->shippingProfilesV1CreateShippingProfileWithHttpInfo($authorization, $createShippingProfileRequestShippingProfilesV1, $contentType);
        return $response;
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfileWithHttpInfo
     *
     * Create shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 create shipping profile (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1CreateShippingProfile'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIErrorResponseForBadRequestShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIErrorResponseForConflictShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1CreateShippingProfileWithHttpInfo($authorization, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1CreateShippingProfile'][0])
    {
        $request = $this->shippingProfilesV1CreateShippingProfileRequest($authorization, $createShippingProfileRequestShippingProfilesV1, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if ('\OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Otto\Model\APIErrorResponseForBadRequestShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\APIErrorResponseForBadRequestShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\APIErrorResponseForBadRequestShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\OpenAPI\Client\Otto\Model\APIErrorResponseForConflictShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\APIErrorResponseForConflictShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\APIErrorResponseForConflictShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIErrorResponseForBadRequestShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIErrorResponseForConflictShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfileAsync
     *
     * Create shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 create shipping profile (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1CreateShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1CreateShippingProfileAsync($authorization, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1CreateShippingProfile'][0])
    {
        return $this->shippingProfilesV1CreateShippingProfileAsyncWithHttpInfo($authorization, $createShippingProfileRequestShippingProfilesV1, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1CreateShippingProfileAsyncWithHttpInfo
     *
     * Create shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 create shipping profile (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1CreateShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1CreateShippingProfileAsyncWithHttpInfo($authorization, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1CreateShippingProfile'][0])
    {
        $returnType = '\OpenAPI\Client\Otto\Model\CreateShippingProfileResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1CreateShippingProfileRequest($authorization, $createShippingProfileRequestShippingProfilesV1, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1CreateShippingProfile'
     *
     * @param  string $authorization Access Token (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 create shipping profile (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1CreateShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingProfilesV1CreateShippingProfileRequest($authorization, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1CreateShippingProfile'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1CreateShippingProfile'
            );
        }

        // verify the required parameter 'createShippingProfileRequestShippingProfilesV1' is set
        if ($createShippingProfileRequestShippingProfilesV1 === null || (is_array($createShippingProfileRequestShippingProfilesV1) && count($createShippingProfileRequestShippingProfilesV1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $createShippingProfileRequestShippingProfilesV1 when calling shippingProfilesV1CreateShippingProfile'
            );
        }


        $resourcePath = '/v1/shipping-profiles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createShippingProfileRequestShippingProfilesV1)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($createShippingProfileRequestShippingProfilesV1));
            } else {
                $httpBody = $createShippingProfileRequestShippingProfilesV1;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfile
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1DeleteShippingProfile'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function shippingProfilesV1DeleteShippingProfile($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1DeleteShippingProfile'][0])
    {
        $this->shippingProfilesV1DeleteShippingProfileWithHttpInfo($authorization, $shippingProfileId, $contentType);
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfileWithHttpInfo
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1DeleteShippingProfile'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1DeleteShippingProfileWithHttpInfo($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1DeleteShippingProfile'][0])
    {
        $request = $this->shippingProfilesV1DeleteShippingProfileRequest($authorization, $shippingProfileId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 412:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIErrorResponseForPreconditionShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfileAsync
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1DeleteShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1DeleteShippingProfileAsync($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1DeleteShippingProfile'][0])
    {
        return $this->shippingProfilesV1DeleteShippingProfileAsyncWithHttpInfo($authorization, $shippingProfileId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1DeleteShippingProfileAsyncWithHttpInfo
     *
     * Delete shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1DeleteShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1DeleteShippingProfileAsyncWithHttpInfo($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1DeleteShippingProfile'][0])
    {
        $returnType = '';
        $request = $this->shippingProfilesV1DeleteShippingProfileRequest($authorization, $shippingProfileId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1DeleteShippingProfile'
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1DeleteShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingProfilesV1DeleteShippingProfileRequest($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1DeleteShippingProfile'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1DeleteShippingProfile'
            );
        }

        // verify the required parameter 'shippingProfileId' is set
        if ($shippingProfileId === null || (is_array($shippingProfileId) && count($shippingProfileId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shippingProfileId when calling shippingProfilesV1DeleteShippingProfile'
            );
        }


        $resourcePath = '/v1/shipping-profiles/{shippingProfileId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shippingProfileId !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingProfileId' . '}',
                ObjectSerializer::toPathValue($shippingProfileId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileById
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfileById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1
     */
    public function shippingProfilesV1GetShippingProfileById($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfileById'][0])
    {
        list($response) = $this->shippingProfilesV1GetShippingProfileByIdWithHttpInfo($authorization, $shippingProfileId, $contentType);
        return $response;
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileByIdWithHttpInfo
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfileById'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1GetShippingProfileByIdWithHttpInfo($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfileById'][0])
    {
        $request = $this->shippingProfilesV1GetShippingProfileByIdRequest($authorization, $shippingProfileId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileByIdAsync
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfileById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfileByIdAsync($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfileById'][0])
    {
        return $this->shippingProfilesV1GetShippingProfileByIdAsyncWithHttpInfo($authorization, $shippingProfileId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfileByIdAsyncWithHttpInfo
     *
     * Get shipping profile by shipping profile id
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfileById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfileByIdAsyncWithHttpInfo($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfileById'][0])
    {
        $returnType = '\OpenAPI\Client\Otto\Model\GetShippingProfileResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1GetShippingProfileByIdRequest($authorization, $shippingProfileId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1GetShippingProfileById'
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfileById'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingProfilesV1GetShippingProfileByIdRequest($authorization, $shippingProfileId, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfileById'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1GetShippingProfileById'
            );
        }

        // verify the required parameter 'shippingProfileId' is set
        if ($shippingProfileId === null || (is_array($shippingProfileId) && count($shippingProfileId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shippingProfileId when calling shippingProfilesV1GetShippingProfileById'
            );
        }


        $resourcePath = '/v1/shipping-profiles/{shippingProfileId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shippingProfileId !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingProfileId' . '}',
                ObjectSerializer::toPathValue($shippingProfileId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json;charset=UTF-8', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfiles
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string|null $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfiles'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1
     */
    public function shippingProfilesV1GetShippingProfiles($authorization, $cursor = null, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfiles'][0])
    {
        list($response) = $this->shippingProfilesV1GetShippingProfilesWithHttpInfo($authorization, $cursor, $contentType);
        return $response;
    }

    /**
     * Operation shippingProfilesV1GetShippingProfilesWithHttpInfo
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string|null $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfiles'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1|\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1GetShippingProfilesWithHttpInfo($authorization, $cursor = null, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfiles'][0])
    {
        $request = $this->shippingProfilesV1GetShippingProfilesRequest($authorization, $cursor, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1GetShippingProfilesAsync
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string|null $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfiles'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfilesAsync($authorization, $cursor = null, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfiles'][0])
    {
        return $this->shippingProfilesV1GetShippingProfilesAsyncWithHttpInfo($authorization, $cursor, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1GetShippingProfilesAsyncWithHttpInfo
     *
     * Get all shipping profiles from a partner
     *
     * @param  string $authorization Access Token (required)
     * @param  string|null $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfiles'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1GetShippingProfilesAsyncWithHttpInfo($authorization, $cursor = null, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfiles'][0])
    {
        $returnType = '\OpenAPI\Client\Otto\Model\GetAllShippingProfilesResponseShippingProfilesV1';
        $request = $this->shippingProfilesV1GetShippingProfilesRequest($authorization, $cursor, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1GetShippingProfiles'
     *
     * @param  string $authorization Access Token (required)
     * @param  string|null $cursor Page number to fetch. This parameter is required to fetch data for specific page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1GetShippingProfiles'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingProfilesV1GetShippingProfilesRequest($authorization, $cursor = null, string $contentType = self::contentTypes['shippingProfilesV1GetShippingProfiles'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1GetShippingProfiles'
            );
        }



        $resourcePath = '/v1/shipping-profiles';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json;charset=UTF-8', 'application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfile
     *
     * Update shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 shipping profile request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1UpdateShippingProfile'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function shippingProfilesV1UpdateShippingProfile($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1UpdateShippingProfile'][0])
    {
        $this->shippingProfilesV1UpdateShippingProfileWithHttpInfo($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, $contentType);
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfileWithHttpInfo
     *
     * Update shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 shipping profile request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1UpdateShippingProfile'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Otto\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function shippingProfilesV1UpdateShippingProfileWithHttpInfo($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1UpdateShippingProfile'][0])
    {
        $request = $this->shippingProfilesV1UpdateShippingProfileRequest($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIErrorResponseForBadRequestShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIErrorResponseForNotFoundShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Otto\Model\APIInternalServerErrorResponseShippingProfilesV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfileAsync
     *
     * Update shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 shipping profile request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1UpdateShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1UpdateShippingProfileAsync($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1UpdateShippingProfile'][0])
    {
        return $this->shippingProfilesV1UpdateShippingProfileAsyncWithHttpInfo($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation shippingProfilesV1UpdateShippingProfileAsyncWithHttpInfo
     *
     * Update shipping profile
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 shipping profile request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1UpdateShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function shippingProfilesV1UpdateShippingProfileAsyncWithHttpInfo($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1UpdateShippingProfile'][0])
    {
        $returnType = '';
        $request = $this->shippingProfilesV1UpdateShippingProfileRequest($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'shippingProfilesV1UpdateShippingProfile'
     *
     * @param  string $authorization Access Token (required)
     * @param  string $shippingProfileId The id of the shipping profile in uuid4 format and the primaryKey for mapping a Profile to a SKU (required)
     * @param  \OpenAPI\Client\Otto\Model\CreateShippingProfileRequestShippingProfilesV1 $createShippingProfileRequestShippingProfilesV1 shipping profile request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['shippingProfilesV1UpdateShippingProfile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function shippingProfilesV1UpdateShippingProfileRequest($authorization, $shippingProfileId, $createShippingProfileRequestShippingProfilesV1, string $contentType = self::contentTypes['shippingProfilesV1UpdateShippingProfile'][0])
    {

        // verify the required parameter 'authorization' is set
        if ($authorization === null || (is_array($authorization) && count($authorization) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $authorization when calling shippingProfilesV1UpdateShippingProfile'
            );
        }

        // verify the required parameter 'shippingProfileId' is set
        if ($shippingProfileId === null || (is_array($shippingProfileId) && count($shippingProfileId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shippingProfileId when calling shippingProfilesV1UpdateShippingProfile'
            );
        }

        // verify the required parameter 'createShippingProfileRequestShippingProfilesV1' is set
        if ($createShippingProfileRequestShippingProfilesV1 === null || (is_array($createShippingProfileRequestShippingProfilesV1) && count($createShippingProfileRequestShippingProfilesV1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $createShippingProfileRequestShippingProfilesV1 when calling shippingProfilesV1UpdateShippingProfile'
            );
        }


        $resourcePath = '/v1/shipping-profiles/{shippingProfileId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($authorization !== null) {
            $headerParams['Authorization'] = ObjectSerializer::toHeaderValue($authorization);
        }

        // path params
        if ($shippingProfileId !== null) {
            $resourcePath = str_replace(
                '{' . 'shippingProfileId' . '}',
                ObjectSerializer::toPathValue($shippingProfileId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($createShippingProfileRequestShippingProfilesV1)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($createShippingProfileRequestShippingProfilesV1));
            } else {
                $httpBody = $createShippingProfileRequestShippingProfilesV1;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
