<?php
/**
 * InitialDiscountOrdersV4
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Otto\Model;

use \ArrayAccess;
use \OpenAPI\Client\Otto\ObjectSerializer;

/**
 * InitialDiscountOrdersV4 Class Doc Comment
 *
 * @category Class
 * @description InitialDiscount
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InitialDiscountOrdersV4 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InitialDiscount__Orders-V4';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'discountAmount' => '\OpenAPI\Client\Otto\Model\AmountOrdersV4',
        'discountId' => 'string',
        'discountName' => 'string',
        'name' => 'string',
        'positionItemIds' => 'string[]',
        'vatRate' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'discountAmount' => null,
        'discountId' => null,
        'discountName' => null,
        'name' => null,
        'positionItemIds' => null,
        'vatRate' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'discountAmount' => false,
        'discountId' => false,
        'discountName' => false,
        'name' => false,
        'positionItemIds' => false,
        'vatRate' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'discountAmount' => 'discountAmount',
        'discountId' => 'discountId',
        'discountName' => 'discountName',
        'name' => 'name',
        'positionItemIds' => 'positionItemIds',
        'vatRate' => 'vatRate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'discountAmount' => 'setDiscountAmount',
        'discountId' => 'setDiscountId',
        'discountName' => 'setDiscountName',
        'name' => 'setName',
        'positionItemIds' => 'setPositionItemIds',
        'vatRate' => 'setVatRate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'discountAmount' => 'getDiscountAmount',
        'discountId' => 'getDiscountId',
        'discountName' => 'getDiscountName',
        'name' => 'getName',
        'positionItemIds' => 'getPositionItemIds',
        'vatRate' => 'getVatRate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('discountAmount', $data ?? [], null);
        $this->setIfExists('discountId', $data ?? [], null);
        $this->setIfExists('discountName', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('positionItemIds', $data ?? [], null);
        $this->setIfExists('vatRate', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['discountAmount'] === null) {
            $invalidProperties[] = "'discountAmount' can't be null";
        }
        if ($this->container['discountId'] === null) {
            $invalidProperties[] = "'discountId' can't be null";
        }
        if ($this->container['discountName'] === null) {
            $invalidProperties[] = "'discountName' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['positionItemIds'] === null) {
            $invalidProperties[] = "'positionItemIds' can't be null";
        }
        if ($this->container['vatRate'] === null) {
            $invalidProperties[] = "'vatRate' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets discountAmount
     *
     * @return \OpenAPI\Client\Otto\Model\AmountOrdersV4
     */
    public function getDiscountAmount()
    {
        return $this->container['discountAmount'];
    }

    /**
     * Sets discountAmount
     *
     * @param \OpenAPI\Client\Otto\Model\AmountOrdersV4 $discountAmount discountAmount
     *
     * @return self
     */
    public function setDiscountAmount($discountAmount)
    {
        if (is_null($discountAmount)) {
            throw new \InvalidArgumentException('non-nullable discountAmount cannot be null');
        }
        $this->container['discountAmount'] = $discountAmount;

        return $this;
    }

    /**
     * Gets discountId
     *
     * @return string
     */
    public function getDiscountId()
    {
        return $this->container['discountId'];
    }

    /**
     * Sets discountId
     *
     * @param string $discountId The id of this discount
     *
     * @return self
     */
    public function setDiscountId($discountId)
    {
        if (is_null($discountId)) {
            throw new \InvalidArgumentException('non-nullable discountId cannot be null');
        }
        $this->container['discountId'] = $discountId;

        return $this;
    }

    /**
     * Gets discountName
     *
     * @return string
     */
    public function getDiscountName()
    {
        return $this->container['discountName'];
    }

    /**
     * Sets discountName
     *
     * @param string $discountName The name of this discount
     *
     * @return self
     */
    public function setDiscountName($discountName)
    {
        if (is_null($discountName)) {
            throw new \InvalidArgumentException('non-nullable discountName cannot be null');
        }
        $this->container['discountName'] = $discountName;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The type of this discount
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets positionItemIds
     *
     * @return string[]
     */
    public function getPositionItemIds()
    {
        return $this->container['positionItemIds'];
    }

    /**
     * Sets positionItemIds
     *
     * @param string[] $positionItemIds The position item ids to which this discount applies
     *
     * @return self
     */
    public function setPositionItemIds($positionItemIds)
    {
        if (is_null($positionItemIds)) {
            throw new \InvalidArgumentException('non-nullable positionItemIds cannot be null');
        }
        $this->container['positionItemIds'] = $positionItemIds;

        return $this;
    }

    /**
     * Gets vatRate
     *
     * @return float
     */
    public function getVatRate()
    {
        return $this->container['vatRate'];
    }

    /**
     * Sets vatRate
     *
     * @param float $vatRate The highest VAT rate between discounted products
     *
     * @return self
     */
    public function setVatRate($vatRate)
    {
        if (is_null($vatRate)) {
            throw new \InvalidArgumentException('non-nullable vatRate cannot be null');
        }
        $this->container['vatRate'] = $vatRate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


