<?php
/**
 * PriceReductionResponsePriceReductionsV1
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Otto\Model;

use \ArrayAccess;
use \OpenAPI\Client\Otto\ObjectSerializer;

/**
 * PriceReductionResponsePriceReductionsV1 Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PriceReductionResponsePriceReductionsV1 implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PriceReductionResponse__Price-Reductions-V1';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'salesOrderId' => 'string',
        'totalPriceReduction' => '\OpenAPI\Client\Otto\Model\PriceReductionResponsePriceReductionsV1TotalPriceReduction',
        'invoicePrice' => '\OpenAPI\Client\Otto\Model\PriceReductionResponsePriceReductionsV1InvoicePrice',
        'priceReductions' => '\OpenAPI\Client\Otto\Model\PriceReductionDetailPriceReductionsV1[]',
        'positionItemId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'salesOrderId' => 'uuid',
        'totalPriceReduction' => null,
        'invoicePrice' => null,
        'priceReductions' => null,
        'positionItemId' => 'uuid'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'salesOrderId' => false,
        'totalPriceReduction' => false,
        'invoicePrice' => false,
        'priceReductions' => false,
        'positionItemId' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'salesOrderId' => 'salesOrderId',
        'totalPriceReduction' => 'totalPriceReduction',
        'invoicePrice' => 'invoicePrice',
        'priceReductions' => 'priceReductions',
        'positionItemId' => 'positionItemId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'salesOrderId' => 'setSalesOrderId',
        'totalPriceReduction' => 'setTotalPriceReduction',
        'invoicePrice' => 'setInvoicePrice',
        'priceReductions' => 'setPriceReductions',
        'positionItemId' => 'setPositionItemId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'salesOrderId' => 'getSalesOrderId',
        'totalPriceReduction' => 'getTotalPriceReduction',
        'invoicePrice' => 'getInvoicePrice',
        'priceReductions' => 'getPriceReductions',
        'positionItemId' => 'getPositionItemId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('salesOrderId', $data ?? [], null);
        $this->setIfExists('totalPriceReduction', $data ?? [], null);
        $this->setIfExists('invoicePrice', $data ?? [], null);
        $this->setIfExists('priceReductions', $data ?? [], null);
        $this->setIfExists('positionItemId', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets salesOrderId
     *
     * @return string|null
     */
    public function getSalesOrderId()
    {
        return $this->container['salesOrderId'];
    }

    /**
     * Sets salesOrderId
     *
     * @param string|null $salesOrderId salesOrderId for an item
     *
     * @return self
     */
    public function setSalesOrderId($salesOrderId)
    {
        if (is_null($salesOrderId)) {
            throw new \InvalidArgumentException('non-nullable salesOrderId cannot be null');
        }
        $this->container['salesOrderId'] = $salesOrderId;

        return $this;
    }

    /**
     * Gets totalPriceReduction
     *
     * @return \OpenAPI\Client\Otto\Model\PriceReductionResponsePriceReductionsV1TotalPriceReduction|null
     */
    public function getTotalPriceReduction()
    {
        return $this->container['totalPriceReduction'];
    }

    /**
     * Sets totalPriceReduction
     *
     * @param \OpenAPI\Client\Otto\Model\PriceReductionResponsePriceReductionsV1TotalPriceReduction|null $totalPriceReduction totalPriceReduction
     *
     * @return self
     */
    public function setTotalPriceReduction($totalPriceReduction)
    {
        if (is_null($totalPriceReduction)) {
            throw new \InvalidArgumentException('non-nullable totalPriceReduction cannot be null');
        }
        $this->container['totalPriceReduction'] = $totalPriceReduction;

        return $this;
    }

    /**
     * Gets invoicePrice
     *
     * @return \OpenAPI\Client\Otto\Model\PriceReductionResponsePriceReductionsV1InvoicePrice|null
     */
    public function getInvoicePrice()
    {
        return $this->container['invoicePrice'];
    }

    /**
     * Sets invoicePrice
     *
     * @param \OpenAPI\Client\Otto\Model\PriceReductionResponsePriceReductionsV1InvoicePrice|null $invoicePrice invoicePrice
     *
     * @return self
     */
    public function setInvoicePrice($invoicePrice)
    {
        if (is_null($invoicePrice)) {
            throw new \InvalidArgumentException('non-nullable invoicePrice cannot be null');
        }
        $this->container['invoicePrice'] = $invoicePrice;

        return $this;
    }

    /**
     * Gets priceReductions
     *
     * @return \OpenAPI\Client\Otto\Model\PriceReductionDetailPriceReductionsV1[]|null
     */
    public function getPriceReductions()
    {
        return $this->container['priceReductions'];
    }

    /**
     * Sets priceReductions
     *
     * @param \OpenAPI\Client\Otto\Model\PriceReductionDetailPriceReductionsV1[]|null $priceReductions all price reductions applied for an item
     *
     * @return self
     */
    public function setPriceReductions($priceReductions)
    {
        if (is_null($priceReductions)) {
            throw new \InvalidArgumentException('non-nullable priceReductions cannot be null');
        }
        $this->container['priceReductions'] = $priceReductions;

        return $this;
    }

    /**
     * Gets positionItemId
     *
     * @return string|null
     */
    public function getPositionItemId()
    {
        return $this->container['positionItemId'];
    }

    /**
     * Sets positionItemId
     *
     * @param string|null $positionItemId positionItemId for an item
     *
     * @return self
     */
    public function setPositionItemId($positionItemId)
    {
        if (is_null($positionItemId)) {
            throw new \InvalidArgumentException('non-nullable positionItemId cannot be null');
        }
        $this->container['positionItemId'] = $positionItemId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


