<?php
/**
 * ContentChangeProductsV5SandboxOnlyTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Otto\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ContentChangeProductsV5SandboxOnlyTest Class Doc Comment
 *
 * @category    Class
 * @description ContentChangeProductsV5SandboxOnly
 * @package     OpenAPI\Client\Otto
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ContentChangeProductsV5SandboxOnlyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ContentChangeProductsV5SandboxOnly"
     */
    public function testContentChangeProductsV5SandboxOnly()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "productReference"
     */
    public function testPropertyProductReference()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shopLink"
     */
    public function testPropertyShopLink()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "lastContentChange"
     */
    public function testPropertyLastContentChange()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
