<?php
/**
 * ProductsV3ApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OTTO Market API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Otto\Test\Api;

use \OpenAPI\Client\Otto\Configuration;
use \OpenAPI\Client\Otto\ApiException;
use \OpenAPI\Client\Otto\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductsV3ApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Otto
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductsV3ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for productsV3CreateOrUpdateProductVariations
     *
     * Create or update product variations.
     *
     */
    public function testProductsV3CreateOrUpdateProductVariations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3FailedByProcessId
     *
     * List failed products of a product data delivery.
     *
     */
    public function testProductsV3FailedByProcessId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetActiveStatus
     *
     * Read active status.
     *
     */
    public function testProductsV3GetActiveStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetBrands
     *
     * List of allowed brands.
     *
     */
    public function testProductsV3GetBrands()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetCategoryGroups
     *
     * Read product categories.
     *
     */
    public function testProductsV3GetCategoryGroups()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetContentChanges
     *
     * Read content changes for a single product variation.
     *
     */
    public function testProductsV3GetContentChanges()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetContentChanges2
     *
     * Read content changes within time period.
     *
     */
    public function testProductsV3GetContentChanges2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetMarketPlaceStatus
     *
     * Read marketplace status for a single product variation.
     *
     */
    public function testProductsV3GetMarketPlaceStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetMarketPlaceStatusList
     *
     * Read marketplace status of product variations.
     *
     */
    public function testProductsV3GetMarketPlaceStatusList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetPartnerProducts
     *
     * Read product variations.
     *
     */
    public function testProductsV3GetPartnerProducts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetProductVariation
     *
     * Read a single product variation.
     *
     */
    public function testProductsV3GetProductVariation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetProductVariationPrice
     *
     * Read a single product variation price.
     *
     */
    public function testProductsV3GetProductVariationPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetProductVariationPrices
     *
     * Read product variations prices.
     *
     */
    public function testProductsV3GetProductVariationPrices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3GetVariationActiveStatus
     *
     * Read the active status of a single product variation.
     *
     */
    public function testProductsV3GetVariationActiveStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3ProgressByProcessId
     *
     * Request the results of a product data delivery.
     *
     */
    public function testProductsV3ProgressByProcessId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3SucceededByProcessId
     *
     * List succeeded products of a product data delivery.
     *
     */
    public function testProductsV3SucceededByProcessId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3UnchangedByProcessId
     *
     * List unchanged products of a product data delivery.
     *
     */
    public function testProductsV3UnchangedByProcessId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3UpdateActiveStatus
     *
     * Update active status.
     *
     */
    public function testProductsV3UpdateActiveStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for productsV3UpdateProductVariationPrices
     *
     * Update product variation prices.
     *
     */
    public function testProductsV3UpdateProductVariationPrices()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
